//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Shop
//  @ File Name : CUSTOMER.cs
//  @ Date : 12-09-2018
//  @ Author : 
//
//


public class CUSTOMER 
{
	public object NAME ;
	public object ADDRESS ;
	public object EMAIL ID ;
	public object TYPE ;
	public void UpdateProfile()
	{
	}
}
