//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Shop
//  @ File Name : Purchase.cs
//  @ Date : 12-09-2018
//  @ Author : 
//
//


public class Purchase 
{
	public object Orderid ;
	public object CustId ;
	public void Discount()
	{
        // EMPLOYEE
        if (CustId.ID<10000)
           BillAmt=  GenerateBill() ;
               final = BillAmt*30/100;
        // Affiliate
        if (CustId.ID>50000 && CustId.ID<100000 )
           BillAmt=  GenerateBill() 
               final = BillAmt*10/100;
        //2Years Customer
        if (CustId.ID>100000 )
           BillAmt=  GenerateBill() 
               final = BillAmt*5/100;
        
	}
	public void GenerateBill()
	{
        if (Grocery)
            Amount = Amount - GroceryAmt;

        if (Amount > 100)
            Deduction = Amount % 100;
        Amount = Amount - Deduction;

        return Amount;

	}
}
