//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Shop
//  @ File Name : SHOPPING CART.cs
//  @ Date : 12-09-2018
//  @ Author : 
//
//


public class SHOPPING CART 
{
	public object Prod id ;
	public object Qty ;
	public void additem()
	{
	}
	public void deleteItem()
	{
	}
	public void ChkOut()
	{
	}
}
