//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Shop
//  @ File Name : USER.cs
//  @ Date : 12-09-2018
//  @ Author : 
//
//


public class USER 
{
	public object USER ID ;
	public object PWD ;
	public void Verify()
	{
	}
}
